name: resume build

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths-ignore:
      - '**/README.md'
      - LICENSE
  pull_request:
    types: [closed]
    branches:
      - main
    paths-ignore:
      - '**/README.md'
      - LICENSE

jobs:
  test:
    name: 'test'
    if: "!contains(github.event.head_commit.message, 'skip ci') || !contains(github.event.head_commit.message, 'build(deps)')"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4.0.2
        with:
          node-version: 16
      - name: install resume-cli
        run: npm install -g resume-cli
      - name: Validate resume
        working-directory: ./src
        run: resume validate --resume stijncallebaut.resume.json

  release:
    name: release
    if: "!contains(github.event.head_commit.message, 'skip ci') || !contains(github.event.head_commit.message, 'build(deps)')"
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4.0.2
      - name: Add plugin for conventional commits
        run: npm install @semantic-release/git -D && npm install @semantic-release/changelog -D && npm install @google/semantic-release-replace-plugin -D
      - name: Get current date
        id: date
        run: echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT
      - name: update resume.json
        run: echo "`jq '.meta.lastModified="${{ steps.date.outputs.date }}"' stijncallebaut.resume.json`" > stijncallebaut.resume.json
        working-directory: ./src
      - name: Release to Github
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GIT_AUTHOR_NAME: "callebaut-bot"
          GIT_AUTHOR_EMAIL: "info@callebaut.dev"
          GIT_COMMITTER_NAME: "callebaut-bot"
          GIT_COMMITTER_EMAIL: "info@callebaut-dev"
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          repository: stijnc/personal-site
          event-type: my-resume
          client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'